import jsPDF from "jspdf";

const MARGIN = 20;
const PAGE_W = 210; // A4 width in mm
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 6;
const FONT_SIZE = 11;
const TITLE_SIZE = 14;
const SMALL_SIZE = 9;

function addHeader(doc: jsPDF, title: string): number {
  let y = MARGIN;
  doc.setFontSize(TITLE_SIZE);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN, y);
  y += LINE_H + 2;

  doc.setFontSize(SMALL_SIZE);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`StatMate — ${new Date().toLocaleDateString()}`, MARGIN, y);
  doc.setTextColor(0);
  y += LINE_H + 4;

  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  return y;
}

function addSection(doc: jsPDF, y: number, label: string, value: string): number {
  if (y > 270) { doc.addPage(); y = MARGIN; }
  doc.setFontSize(FONT_SIZE);
  doc.setFont("helvetica", "bold");
  doc.text(label, MARGIN, y);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(value, CONTENT_W);
  doc.text(lines, MARGIN, y + LINE_H);
  return y + LINE_H + lines.length * LINE_H + 2;
}

function addTable(doc: jsPDF, y: number, headers: string[], rows: string[][]): number {
  if (y > 250) { doc.addPage(); y = MARGIN; }
  const colW = CONTENT_W / headers.length;

  // Header
  doc.setFillColor(245, 245, 245);
  doc.rect(MARGIN, y - 4, CONTENT_W, LINE_H + 2, "F");
  doc.setFontSize(SMALL_SIZE);
  doc.setFont("helvetica", "bold");
  headers.forEach((h, i) => {
    doc.text(h, MARGIN + i * colW + 2, y);
  });
  y += LINE_H + 1;

  // Rows
  doc.setFont("helvetica", "normal");
  for (const row of rows) {
    if (y > 275) { doc.addPage(); y = MARGIN; }
    row.forEach((cell, i) => {
      doc.text(cell, MARGIN + i * colW + 2, y);
    });
    y += LINE_H;
  }
  y += 4;
  return y;
}

function addApa(doc: jsPDF, y: number, apa: string): number {
  if (y > 260) { doc.addPage(); y = MARGIN; }
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 4;

  doc.setFontSize(SMALL_SIZE);
  doc.setFont("helvetica", "bolditalic");
  doc.text("APA Result:", MARGIN, y);
  y += LINE_H;

  doc.setFont("helvetica", "italic");
  const lines = doc.splitTextToSize(apa, CONTENT_W);
  doc.text(lines, MARGIN, y);
  y += lines.length * LINE_H + 4;
  return y;
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150);
    doc.text("Generated by StatMate (statmate-red.vercel.app)", MARGIN, 290);
    doc.text(`Page ${i}/${pages}`, PAGE_W - MARGIN - 15, 290);
    doc.setTextColor(0);
  }
}

function toBlob(doc: jsPDF): Blob {
  return doc.output("blob");
}

// --- T-Test PDF ---
export function exportTTestPdf(data: {
  type: string; t: number; df: number; pValue: number; cohensD: number;
  ci95: [number, number]; meanDiff: number;
  group1Stats: { mean: number; sd: number; n: number };
  group2Stats: { mean: number; sd: number; n: number };
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, data.type === "independent" ? "Independent Samples t-Test" : "Paired Samples t-Test");

  y = addTable(doc, y,
    ["Group", "N", "M", "SD"],
    [
      [data.type === "independent" ? "Group 1" : "Time 1", String(data.group1Stats.n), data.group1Stats.mean.toFixed(2), data.group1Stats.sd.toFixed(2)],
      [data.type === "independent" ? "Group 2" : "Time 2", String(data.group2Stats.n), data.group2Stats.mean.toFixed(2), data.group2Stats.sd.toFixed(2)],
    ]
  );

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["t", data.t.toFixed(4)],
      ["df", data.type === "independent" ? data.df.toFixed(2) : String(data.df)],
      ["p (two-tailed)", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ["Cohen's d", data.cohensD.toFixed(4)],
      ["Mean difference", data.meanDiff.toFixed(4)],
      ["95% CI", `[${data.ci95[0].toFixed(4)}, ${data.ci95[1].toFixed(4)}]`],
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- ANOVA PDF ---
export function exportAnovaPdf(data: {
  fStatistic: number; dfBetween: number; dfWithin: number; pValue: number;
  etaSquared: number; ssBetween: number; ssWithin: number; ssTotal: number;
  msBetween: number; msWithin: number;
  groupStats: { name: string; n: number; mean: number; sd: number }[];
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "One-Way ANOVA");

  y = addTable(doc, y,
    ["Source", "SS", "df", "MS", "F", "p"],
    [
      ["Between", data.ssBetween.toFixed(2), String(data.dfBetween), data.msBetween.toFixed(2), data.fStatistic.toFixed(2), data.pValue < .001 ? "< .001" : data.pValue.toFixed(3)],
      ["Within", data.ssWithin.toFixed(2), String(data.dfWithin), data.msWithin.toFixed(2), "", ""],
      ["Total", data.ssTotal.toFixed(2), String(data.dfBetween + data.dfWithin), "", "", ""],
    ]
  );

  y = addSection(doc, y, "Effect Size:", `eta-squared = ${data.etaSquared.toFixed(4)}`);

  y = addTable(doc, y,
    ["Group", "N", "M", "SD"],
    data.groupStats.map(g => [g.name, String(g.n), g.mean.toFixed(2), g.sd.toFixed(2)])
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Chi-Square PDF ---
export function exportChiSquarePdf(data: {
  type: string; chiSquare: number; df: number; pValue: number;
  cramersV?: number; observed: number[][] | number[]; expected: number[][] | number[];
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, data.type === "independence" ? "Chi-Square Test of Independence" : "Chi-Square Goodness-of-Fit");

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["Chi-square", data.chiSquare.toFixed(4)],
      ["df", String(data.df)],
      ["p", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ...(data.cramersV != null ? [["Cramer's V", data.cramersV.toFixed(4)]] : []),
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Correlation PDF ---
export function exportCorrelationPdf(data: {
  type: string; r: number; t: number; df: number; pValue: number;
  ci95: [number, number]; n: number; r2: number;
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, `${data.type === "pearson" ? "Pearson" : "Spearman"} Correlation`);

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      [data.type === "pearson" ? "r" : "rho", data.r.toFixed(4)],
      ["R-squared", data.r2.toFixed(4)],
      ["t", data.t.toFixed(4)],
      ["df", String(data.df)],
      ["p (two-tailed)", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ["95% CI", `[${data.ci95[0].toFixed(4)}, ${data.ci95[1].toFixed(4)}]`],
      ["N", String(data.n)],
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Descriptive PDF ---
export function exportDescriptivePdf(data: {
  n: number; mean: number; median: number; sd: number; variance: number;
  se: number; min: number; max: number; range: number;
  q1: number; q3: number; iqr: number;
  skewness: number; kurtosis: number; ci95: [number, number];
}): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "Descriptive Statistics");

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["N", String(data.n)],
      ["Mean", data.mean.toFixed(4)],
      ["Median", data.median.toFixed(4)],
      ["SD", data.sd.toFixed(4)],
      ["Variance", data.variance.toFixed(4)],
      ["SE", data.se.toFixed(4)],
      ["Min", data.min.toFixed(4)],
      ["Max", data.max.toFixed(4)],
      ["Range", data.range.toFixed(4)],
      ["Q1", data.q1.toFixed(4)],
      ["Q3", data.q3.toFixed(4)],
      ["IQR", data.iqr.toFixed(4)],
      ["Skewness", data.skewness.toFixed(4)],
      ["Kurtosis", data.kurtosis.toFixed(4)],
      ["95% CI", `[${data.ci95[0].toFixed(4)}, ${data.ci95[1].toFixed(4)}]`],
    ]
  );

  addFooter(doc);
  return toBlob(doc);
}

// --- One-Sample T PDF ---
export function exportOneSampleTPdf(data: {
  t: number; df: number; pValue: number; cohensD: number;
  ci95: [number, number]; mean: number; sd: number; n: number; testValue: number;
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "One-Sample t-Test");

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["Test value", String(data.testValue)],
      ["N", String(data.n)],
      ["Sample mean", data.mean.toFixed(4)],
      ["SD", data.sd.toFixed(4)],
      ["t", data.t.toFixed(4)],
      ["df", String(data.df)],
      ["p (two-tailed)", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ["Cohen's d", data.cohensD.toFixed(4)],
      ["95% CI", `[${data.ci95[0].toFixed(4)}, ${data.ci95[1].toFixed(4)}]`],
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Mann-Whitney PDF ---
export function exportMannWhitneyPdf(data: {
  uMin: number; z: number; pValue: number; rankBiserialR: number;
  n1: number; n2: number; median1: number; median2: number;
  u1: number; u2: number; meanRank1: number; meanRank2: number;
  effectSizeLabel: string;
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "Mann-Whitney U Test");

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["U", data.uMin.toFixed(2)],
      ["z", data.z.toFixed(4)],
      ["p (two-tailed)", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ["Effect size (r)", data.rankBiserialR.toFixed(4)],
      ["n1", String(data.n1)],
      ["n2", String(data.n2)],
      ["Median (Group 1)", data.median1.toFixed(2)],
      ["Median (Group 2)", data.median2.toFixed(2)],
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Wilcoxon PDF ---
export function exportWilcoxonPdf(data: {
  wStat: number; z: number; pValue: number; rankBiserialR: number;
  n: number; nEffective: number; effectSizeLabel: string;
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "Wilcoxon Signed-Rank Test");

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["W", data.wStat.toFixed(2)],
      ["z", data.z.toFixed(4)],
      ["p (two-tailed)", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ["Effect size (r)", data.rankBiserialR.toFixed(4)],
      ["N", String(data.n)],
      ["N (effective)", String(data.nEffective)],
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Regression PDF ---
export function exportRegressionPdf(data: {
  slope: number; intercept: number; r: number; rSquared: number;
  fStatistic: number; pValue: number; se: number; n: number;
  adjustedRSquared: number;
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "Simple Linear Regression");

  y = addTable(doc, y,
    ["Statistic", "Value"],
    [
      ["Slope (b)", data.slope.toFixed(4)],
      ["Intercept (a)", data.intercept.toFixed(4)],
      ["r", data.r.toFixed(4)],
      ["R-squared", data.rSquared.toFixed(4)],
      ["F", data.fStatistic.toFixed(4)],
      ["p", data.pValue < 0.001 ? "< .001" : data.pValue.toFixed(4)],
      ["SE of estimate", data.se.toFixed(4)],
      ["N", String(data.n)],
    ]
  );

  y = addSection(doc, y, "Equation:", `Y = ${data.intercept.toFixed(4)} + ${data.slope.toFixed(4)} * X`);

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}

// --- Sample Size PDF ---
export function exportSampleSizePdf(data: {
  nTotal: number; nPerGroup: number; effectSize: number;
  effectSizeLabel: string; alpha: number; power: number;
  achievedPower: number; testType: string;
}, apa: string): Blob {
  const doc = new jsPDF();
  let y = addHeader(doc, "Sample Size / Power Analysis");

  y = addTable(doc, y,
    ["Parameter", "Value"],
    [
      ["Test type", data.testType],
      ["Required N (total)", String(data.nTotal)],
      ["N per group", String(data.nPerGroup)],
      ["Effect size", data.effectSize.toFixed(2)],
      ["Effect size label", data.effectSizeLabel],
      ["Alpha", data.alpha.toFixed(2)],
      ["Target power", data.power.toFixed(2)],
      ["Achieved power", `${(data.achievedPower * 100).toFixed(1)}%`],
    ]
  );

  y = addApa(doc, y, apa);
  addFooter(doc);
  return toBlob(doc);
}
