import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "terms" });
  return {
    title: t("metaTitle"),
    description: t("metaDescription"),
    alternates: {
      canonical: "/terms",
      languages: {
        en: "/terms",
        ko: "/ko/terms",
        ja: "/ja/terms",
        "x-default": "/terms",
      },
    },
  };
}

export default async function TermsPage() {
  const t = await getTranslations("terms");

  return (
    <div className="mx-auto max-w-3xl py-8">
      <h1 className="text-3xl font-bold text-gray-900">{t("title")}</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: February 2026</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-gray-600">
        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using StatMate (statmate.org), you agree
            to these Terms of Service. If you do not agree, please do not use
            our service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            2. Service Description
          </h2>
          <p>
            StatMate provides free online statistical calculators with
            APA-formatted results. Additional premium features (AI
            interpretation, Word export) are available through paid
            subscriptions.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            3. Free Tier
          </h2>
          <ul className="ml-4 list-disc space-y-1">
            <li>All statistical calculators are free to use without limits.</li>
            <li>No account or registration is required.</li>
            <li>
              We reserve the right to display advertisements on free tier pages.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            4. Pro Subscription
          </h2>
          <ul className="ml-4 list-disc space-y-1">
            <li>
              Pro subscriptions are billed monthly or annually through Lemon
              Squeezy.
            </li>
            <li>
              A 7-day free trial is available for new subscribers. You will not
              be charged during the trial period.
            </li>
            <li>
              You may cancel your subscription at any time. Access continues
              until the end of the billing period.
            </li>
            <li>Refunds are handled according to Lemon Squeezy&apos;s refund policy.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            5. Accuracy Disclaimer
          </h2>
          <p>
            StatMate is provided as an educational and research assistance tool.
            While we strive for statistical accuracy, results should be verified
            independently for critical research. We are not responsible for
            errors in calculations or interpretations used in publications,
            academic submissions, or professional decisions.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            6. AI Interpretation Disclaimer
          </h2>
          <p>
            AI-generated interpretations are provided for convenience and should
            not be used as the sole basis for research conclusions. Always review
            AI-generated content before including it in academic work.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            7. Intellectual Property
          </h2>
          <p>
            The StatMate name, logo, and website content are our intellectual
            property. You may freely use the statistical results generated by our
            calculators in your research and publications.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            8. Limitation of Liability
          </h2>
          <p>
            StatMate is provided &quot;as is&quot; without warranties of any
            kind. We shall not be liable for any damages arising from the use of
            our service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            9. Changes to Terms
          </h2>
          <p>
            We may update these terms at any time. Continued use of the service
            constitutes acceptance of updated terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-gray-900">
            10. Contact
          </h2>
          <p>
            Questions? Email{" "}
            <a
              href="mailto:contact.statmate@gmail.com"
              className="text-blue-600 underline"
            >
              contact.statmate@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
